FROM node:6.2.0

WORKDIR /gpxprogress.build
COPY package.json /gpxprogress.build/
RUN npm install

COPY run.sh /run.sh
RUN chmod 755 /run.sh

WORKDIR /gpxprogress

ENTRYPOINT ["sh", "/run.sh"]
CMD ["build"]
